rule all:
    input:
        "results/ecoli_k11_report.json",
        "results/top_kmers_k11.csv"

rule rust_kmer_report:
    input:
        fastq="data/subset/ecoli_100k_R1.fastq"
    output:
        json="results/ecoli_k11_report.json",
        csv="results/top_kmers_k11.csv"
    params:
        k=11
    shell:
        "cargo run --release -- {input.fastq} {params.k} {output.json} {output.csv}"